### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [viktordanov/abacus#11]
Dear Viktor,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by viktordanov** [comment]
I will make a release with a Windows binary soon :)

**Comment by viktordanov** [comment]
I've set up automatic releases and added a few new features. 
You will have to use bash if you're gonna be using it on Windows though :sweat_smile:  Either that or use the `--no-color` flag :slightly_smiling_face:
